# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hook.proto',
  package='hook',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nhook.proto\x12\x04hook\"&\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t\"\x18\n\x04Hook\x12\x10\n\x08username\x18\x01 \x01(\t2\x8a\x01\n\x07webHook\x12*\n\nhookCreate\x12\n.hook.User\x1a\x0e.hook.Response\"\x00\x12*\n\nhookUpdate\x12\n.hook.User\x1a\x0e.hook.Response\"\x00\x12\'\n\x07hookGet\x12\n.hook.Hook\x1a\x0e.hook.Response\"\x00\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='hook.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='hook.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link', full_name='hook.User.link', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=58,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='hook.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='hook.Response.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=88,
)


_HOOK = _descriptor.Descriptor(
  name='Hook',
  full_name='hook.Hook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='hook.Hook.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Hook'] = _HOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'hook_pb2'
  # @@protoc_insertion_point(class_scope:hook.User)
  ))
_sym_db.RegisterMessage(User)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'hook_pb2'
  # @@protoc_insertion_point(class_scope:hook.Response)
  ))
_sym_db.RegisterMessage(Response)

Hook = _reflection.GeneratedProtocolMessageType('Hook', (_message.Message,), dict(
  DESCRIPTOR = _HOOK,
  __module__ = 'hook_pb2'
  # @@protoc_insertion_point(class_scope:hook.Hook)
  ))
_sym_db.RegisterMessage(Hook)



_WEBHOOK = _descriptor.ServiceDescriptor(
  name='webHook',
  full_name='hook.webHook',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=117,
  serialized_end=255,
  methods=[
  _descriptor.MethodDescriptor(
    name='hookCreate',
    full_name='hook.webHook.hookCreate',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='hookUpdate',
    full_name='hook.webHook.hookUpdate',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='hookGet',
    full_name='hook.webHook.hookGet',
    index=2,
    containing_service=None,
    input_type=_HOOK,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBHOOK)

DESCRIPTOR.services_by_name['webHook'] = _WEBHOOK

# @@protoc_insertion_point(module_scope)
